#!/bin/bash
source /bin/vcvars
clear
function show_usage() {
    echo -e $LGREEN"\nVC Launcher"$RALL
    printf "Usage: $0 [option]\n"
    printf "\n"
    printf "Options:\n"
    printf " start     | Start VC & KeepassXC\n"
    printf " stop      | Stop VC & KeepassXC\n"
    printf " restart   | Restart VC & KeepassXC\n"
    printf "\n"
    printf " startns   | Start without Sync\n"
    printf " stopns    | Stop without Sync\n"
    printf " restartns | Restart without Sync\n"
    printf "\n"
    printf " backup    | Backup Container\n"
    printf "\n"
    printf " -h|help   | Display this Helpscreen\n"
return 0
}

if [[ $# -gt 2 ]] || [[ $# -eq 0 ]];then
   show_usage
   exit 1
fi

while [ ! -z "$1" ];do
    case "$1" in
        -h|help)
        show_usage
        ;;

        start)
        echo -e $LGREEN"VC Start"$RALL
        if [[ `sudo lsblk -o MOUNTPOINT | grep $ContainerMP/$ContainerName` ]]
        then
            echo -e "\n[\e[36mii\e[39m] Container already mounted!!!"
        else
	        #Check Host is up
	        ping -c1 $sshhost -W0.1 1>/dev/null 2>/dev/null
            SUCCESS=$?
            if [ $SUCCESS -eq 0 ]
            then
                #DL Container
                echo -e $LGREEN"\nLocal | Download (Sync)"$RALL
                echo -e "[\e[92m✓\e[39m] $sshhost has replied"
                sudo scp -P $sshport -i $idpfad $sshuser@$sshhost:"$remoteDir/$ContainerName" $ContainerDir
                [[ -f "$ContainerDir/$ContainerName" ]] && echo -e "\n[\e[92m✓\e[39m] Sync successfully" || echo -e "[\e[91m✗\e[39m] Sync Error"
            else
                echo -e $LGREEN"Local | Download (Sync)\n"$RALL
                echo -e "[\e[91m✗\e[39m] $sshhost didn't reply - NO SYNC"
            fi
            # Mount Container
            sudo veracrypt --mount $ContainerDir/$ContainerName $ContainerMP/$ContainerName -p $vcpw --pim 0 -k '' --protect-hidden 'no' >/dev/null
            [[ `lsblk -o MOUNTPOINT | grep $ContainerMP/$ContainerName` ]] && echo -e "\n[\e[92m✓\e[39m] Container mounted!!.\e[39m"
        fi
        #Check if Keepass is already started
        if [[ `pidof keepassxc` ]]
        then
            echo -e "[\e[36mii\e[39m] KeePassXC already started - Press F5 to Reload!\e[39m"
            exit
        else
            `keepassxc </dev/null &>/dev/null &`
            [[ `pidof keepassxc` ]]
            echo -e "[\e[92m✓\e[39m] KeePassXC started\e[39m"
        fi
        ;;

        stop)
        echo -e $LGREEN"VC Stop"$RALL
        #Check Keepass is closed or not.
        if [[ ! `sudo pidof keepassxc` ]]
        then
            echo -e "\n[\e[36mii\e[39m] KeePassXC already closed!\e[39m"
        else
            #[[ `sudo pidof keepassxc` ]]
            kill `pidof keepassxc`
            [[ ! `pidof keepassxc` ]]
            echo -e "\n[\e[92m✓\e[39m] KeePassXC terminated!\e[39m"
        fi
        #Check Veracrypt Container dismounted, if yes exit.
        if [[ ! `lsblk -o MOUNTPOINT | grep "$ContainerMP/$ContainerName"` ]]
        then
            echo -e "[\e[36mii\e[39m] Container already dismounted!"
            exit
        else
            veracrypt -d $ContainerMP/$ContainerName
            if [[ ! `lsblk -o MOUNTPOINT | grep "$ContainerMP/$ContainerName"` ]]
            then
                echo -e "[\e[92m✓\e[39m] Volume Dismounted!\e[39m"
            else
                echo -e "[\e[91m✗\e[39m] Volume not dismounted! - Exit"
                exit
            fi
        # Check Host is up for upload
        ping -c1 $sshhost -W0.1 1>/dev/null 2>/dev/null
        SUCCESS=$?
	        if [ $SUCCESS -eq 0 ]
	        then
                #Upload
	            echo -e $LGREEN"\nServer | Upload (Sync)"$RALL
	            echo -e "[\e[92m✓\e[39m] $sshhost has replied"
	            sudo scp -P $sshport -i $idpfad $ContainerDir/$ContainerName $sshuser@$sshhost:"$remoteDir"
        	    ssh -q $sshuser@$sshhost -p $sshport -i $idpfad [[ -f "$remoteDir/$ContainerName" ]] && echo -e "\n[\e[92m✓\e[39m] Sync successfully" || echo -e "[\e[91m✗\e[39m] Sync Error"
	        else
	            echo -e $LGREEN"\nServer | Upload (Sync)\n"$RALL
	            echo -e "[\e[91m✗\e[39m] $sshhost didn't reply - NO SYNC"
	        fi
        fi
        ;;

        startns)
        echo -e $LGREEN"VC Start"$RALL" - "$LRED"No Sync"$RALL
        if [[ `sudo lsblk -o MOUNTPOINT | grep $ContainerMP/$ContainerName` ]]
        then
            echo -e "\n[\e[36mii\e[39m] Container already mounted!."
        else
            sudo veracrypt --mount "$ContainerDir/$ContainerName" "$ContainerMP/$ContainerName" -p "$vcpw" --pim 0 -k '' --protect-hidden 'no' >/dev/null
            [[ `lsblk -o MOUNTPOINT | grep $ContainerMP/$ContainerName` ]] && echo -e "\n[\e[92m✓\e[39m] Container mounted!!\e[39m"
        fi
        if [[ `pidof keepassxc` ]]
        then
            echo -e "[\e[36mii\e[39m] KeePassXC already started - Press F5 to Reload!\e[39m"
        else
            `keepassxc </dev/null &>/dev/null &`
            [[ `pidof keepassxc` ]]
            echo -e "[\e[92m✓\e[39m] KeePassXC gestartet\e[39m"
        fi
        ;;

        stopns)
        echo -e $LGREEN"VC Stop"$RALL" - "$LRED"No Sync"$RALL
        if [[ ! `sudo pidof keepassxc` ]]
        then
            echo -e "\n[\e[36mii\e[39m] KeePassXC already closed!\e[39m"
        else
            kill `pidof keepassxc`
            [[ ! `pidof keepassxc` ]]
            echo -e "\n[\e[92m✓\e[39m] KeePassXC terminated!\e[39m"
        fi
        if [[ ! `lsblk -o MOUNTPOINT | grep "/vc/container/Ollicrypt"` ]]
        then
            echo -e "[\e[36mii\e[39m] Container already dismounted!"
            exit
        else
            veracrypt -d $ContainerMP/$ContainerName
            if [[ ! `lsblk -o MOUNTPOINT | grep "$ContainerMP/$ContainerName"` ]]
            then
                echo -e "[\e[92m✓\e[39m] Volume Dismounted!!\e[39m"
            else
                echo -e "[\e[91m✗\e[39m] Volume not dismounted!! - Exit"
                exit
            fi
        fi
        ;;

        backup)
        echo -e $LGREEN"VC Backup"$RALL
        ping -c1 $sshhost -W0.1 1>/dev/null 2>/dev/null
        SUCCESS=$?
        if [ $SUCCESS -eq 0 ]
        then
            echo ""
            ssh -t -t -q $sshuser@$sshhost -p $sshport -i $idpfad 'if [[ ! -d '$remoteDirbackup' ]];
            then mkdir '$remoteDirbackup'
            fi'
            sudo scp -P $sshport -i $idpfad $ContainerDir/$ContainerName $sshuser@$sshhost:"$remoteDirbackup"
            ssh -t -t -q $sshuser@$sshhost -p $sshport -i $idpfad 'if [[ -f '$remoteDir/$ContainerName' ]] && [[ -f '$remoteDirbackup/$ContainerName' ]]
            then echo -e "\n[\e[92m✓\e[39m] FILES exists - Backup successfully"
            else echo -e "[\e[91m✓\e[39m] FILES does not exist"
            fi'
        else
	        echo -e $LRED"\nAborted! $sshhost didn't reply - NO SYNC"$RALL
            exit
        fi
        ;;

        restart)
        echo -e $LGREEN"VC Restart"$RALL
        #stop
        if [[ ! `sudo pidof keepassxc` ]]
        then
            :
        else
            kill `pidof keepassxc`
            [[ ! `pidof keepassxc` ]]
        fi
        if [[ ! `lsblk -o MOUNTPOINT | grep "$ContainerMP/$ContainerName"` ]]
        then
            :
        else
            veracrypt -d $ContainerMP/$ContainerName
            if [[ ! `lsblk -o MOUNTPOINT | grep "$ContainerMP/$ContainerName"` ]]
            then
                :
            else
                echo -e "[\e[91m✗\e[39m] Volume not dismounted!! - Exit"
                exit
            fi
        fi
        #start
        if [[ `sudo lsblk -o MOUNTPOINT | grep '$ContainerMP/$ContainerName'` ]]
        then
            echo -e "\n[\e[36mii\e[39m] Container already mounted!!."
        else
	        ping -c1 $sshhost -W0.1 1>/dev/null 2>/dev/null
            SUCCESS=$?
            if [ $SUCCESS -eq 0 ]
            then
                sudo scp -P $sshport -i $idpfad $sshuser@$sshhost:"$remoteDir/$ContainerName" $ContainerDir >/dev/null
            else
                echo -e $LGREEN"Local | Download (Sync)\n"$RALL
                echo -e "[\e[91m✗\e[39m] $sshhost didn't reply - NO SYNC"
            fi
            sudo veracrypt --mount $ContainerDir/$ContainerName $ContainerMP/$ContainerName -p $vcpw --pim 0 -k '' --protect-hidden 'no' >/dev/null
        fi
        if [[ `pidof keepassxc` ]]
        then
            echo -e "[\e[36mii\e[39m] KeePassXC already started - Press F5 to Reload!\e[39m"
        else
            `keepassxc </dev/null &>/dev/null &`
            [[ `pidof keepassxc` ]]
        fi
        sleep 1
        echo -e "\n[\e[92m✓\e[39m] VC Restart successfully\e[39m"
        ;;

        restartns)
        echo -e $LGREEN"VC Restart"$RALL" - "$LRED"No Sync"$RALL
        if [[ ! `sudo pidof keepassxc` ]]
        then
            echo -e "\n[\e[36mii\e[39m] KeePassXC already closed!\e[39m"
        else
            kill `pidof keepassxc`
            [[ ! `pidof keepassxc` ]]
            echo -e "\n[\e[92m✓\e[39m] KeePassXC terminated!\e[39m"
        fi
        if [[ ! `lsblk -o MOUNTPOINT | grep "$ContainerMP/$ContainerName"` ]]
        then
            echo -e "[\e[36mii\e[39m] Container already dismounted!"
            exit
        else
            veracrypt -d $ContainerMP/$ContainerName
            if [[ ! `lsblk -o MOUNTPOINT | grep "$ContainerMP/$ContainerName"` ]]
            then
                :
            else
                echo -e "[\e[91m✗\e[39m] Volume not dismounted!! - Exit"
                exit
            fi
        fi
        if [[ `sudo lsblk -o MOUNTPOINT | grep "$ContainerMP/$ContainerName"` ]]
        then
            echo -e "\n[\e[36mii\e[39m] Container already mounted!!."
        else
            sudo veracrypt --mount $ContainerDir/$ContainerName $ContainerMP/$ContainerName -p $vcpw --pim 0 -k '' --protect-hidden 'no' >/dev/null
            [[ `lsblk -o MOUNTPOINT | grep "$ContainerMP/$ContainerName"` ]] && echo -e "[\e[92m✓\e[39m] Container mounted!\e[39m"
        fi
        if [[ `pidof keepassxc` ]]
        then
            echo -e "[\e[36mii\e[39m] KeePassXC already started - Press F5 to Reload!\e[39m"
        else
            `keepassxc </dev/null &>/dev/null &`
            [[ `pidof keepassxc` ]]
            echo -e "[\e[92m✓\e[39m] KeePassXC gestartet\e[39m"
        fi
        clear 
        echo -e $LGREEN"VC Restart"$RALL" - "$LRED"No Sync"$RALL"\n\n[\e[92m✓\e[39m] VC Restart successfully\e[39m"
        MINUTEN=$(($SECONDS / 60))
        SEC=$(($SECONDS - $MINUTEN * 60))
        echo -e "[\e[91m$MINUTEN:$SEC\e[39m]"
        ;;

        *)
        echo "Incorrect input provided"
        show_usage
    esac
shift
done

