#!/bin/bash
#Variablen
#Colors
RED='\e[31m'
LRED='\e[91m'
LGREEN='\e[92m'
CYAN='\e[36m'
RALL='\e[0;39;49m' #Remove all Colors u. Effecte
#Date
DATE=$(date +"%d.%m.%Y")

#SSH
sshuser=USER
sshhost=IP/Domain
idpath=/Path/to/your/ssh/key/file
sshport=22
remoteDir="/Remote/DIR/FOR/VeracryptContainer"
remoteDirbackup="/Remote/DIR/FOR/VeracryptContainer"
vcpw=`cat /bin/vcsec`

#Veracrypt
ContainerDir=/Path/to/your/Varacrypt/Containerfile - only Path no Filename!
ContainerName=CONTAINERNAME
ContainerMP=/Path/to/your/Mountpoint <== Where your Container should be mounted.
